name: frontend
description: EmpTracker Pro - Employee Location Tracking App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_background_service: ^5.0.5
  flutter_background_service_android: ^6.2.2
  flutter_local_notifications: ^17.2.2
  camera: ^0.10.5

  image: ^4.1.3
  path_provider: ^2.1.2

  # Fonts
  google_fonts: ^6.1.0
  # Map & Location
  flutter_map: ^7.0.2
  latlong2: ^0.9.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  http: ^1.2.0
  dio: ^5.4.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0 # Secure token storage
  permission_handler: ^11.0.1 # Location permissions
  google_maps_flutter: ^2.5.0
  # Real-time & Network
  socket_io_client: ^2.0.3

  # State Management
  provider: ^6.1.1

  # Utilities
  intl: ^0.19.0

  # UI Components
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: 0.14.4
flutter:
  uses-material-design: true
